// <auto-generated />
using System;
using GalaAuction.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GalaAuction.Server.Migrations
{
    [DbContext(typeof(GalaAuctionDBContext))]
    [Migration("20260218051352_AddedEventDateAndItemTable")]
    partial class AddedEventDateAndItemTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GalaAuction.Server.Models.Bidder", b =>
                {
                    b.Property<int>("BidderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BidderId"));

                    b.Property<string>("BidderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GuestId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.HasKey("BidderId");

                    b.HasIndex("GuestId");

                    b.ToTable("Bidders");

                    b.HasData(
                        new
                        {
                            BidderId = -1,
                            BidderNumber = "1",
                            GuestId = -1,
                            IsOnline = false
                        },
                        new
                        {
                            BidderId = -2,
                            BidderNumber = "2",
                            GuestId = -2,
                            IsOnline = false
                        },
                        new
                        {
                            BidderId = -3,
                            BidderNumber = "ESM",
                            GuestId = -2,
                            IsOnline = true
                        },
                        new
                        {
                            BidderId = -4,
                            BidderNumber = "3",
                            GuestId = -3,
                            IsOnline = false
                        },
                        new
                        {
                            BidderId = -5,
                            BidderNumber = "ER",
                            GuestId = -3,
                            IsOnline = true
                        },
                        new
                        {
                            BidderId = -6,
                            BidderNumber = "4",
                            GuestId = -4,
                            IsOnline = false
                        },
                        new
                        {
                            BidderId = -7,
                            BidderNumber = "5",
                            GuestId = -5,
                            IsOnline = false
                        },
                        new
                        {
                            BidderId = -8,
                            BidderNumber = "PM",
                            GuestId = -5,
                            IsOnline = true
                        });
                });

            modelBuilder.Entity("GalaAuction.Server.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Getaways"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Alcohol"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Restaurants"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Events"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Artwork"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Services"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Orchids"
                        });
                });

            modelBuilder.Entity("GalaAuction.Server.Models.GalaEvent", b =>
                {
                    b.Property<int>("GalaEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GalaEventId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThankYouMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GalaEventId");

                    b.ToTable("GalaEvents");

                    b.HasData(
                        new
                        {
                            GalaEventId = 1,
                            CreatedAt = new DateTime(2026, 2, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            EventName = "Gala 2026",
                            EventStatus = "Setup",
                            OrganizationName = "Canticorum Virtuosi, Inc.",
                            ThankYouMessage = "Thank you for your support!"
                        });
                });

            modelBuilder.Entity("GalaAuction.Server.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GuestId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GalaEventId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("integer");

                    b.HasKey("GuestId");

                    b.HasIndex("GalaEventId");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            GuestId = -1,
                            FirstName = "Stewart",
                            GalaEventId = 1,
                            LastName = "McGuire",
                            TableNumber = 2
                        },
                        new
                        {
                            GuestId = -2,
                            FirstName = "Elisabeth",
                            GalaEventId = 1,
                            LastName = "McDonald",
                            TableNumber = 2
                        },
                        new
                        {
                            GuestId = -3,
                            FirstName = "Edie",
                            GalaEventId = 1,
                            LastName = "Rosenbaum",
                            TableNumber = 1
                        },
                        new
                        {
                            GuestId = -4,
                            FirstName = "Harold",
                            GalaEventId = 1,
                            LastName = "Rosenbaum",
                            TableNumber = 1
                        },
                        new
                        {
                            GuestId = -5,
                            FirstName = "Peggy",
                            GalaEventId = 1,
                            LastName = "McGuire",
                            TableNumber = 2
                        });
                });

            modelBuilder.Entity("GalaAuction.Server.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("GalaEventId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("text");

                    b.Property<decimal?>("WinningBidAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("WinningBidderNumber")
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GalaEventId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("GalaAuction.Server.Models.PaymentMethod", b =>
                {
                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            PaymentMethodId = "AmEx",
                            PaymentMethodName = "American Express"
                        },
                        new
                        {
                            PaymentMethodId = "Cash",
                            PaymentMethodName = "Cash"
                        },
                        new
                        {
                            PaymentMethodId = "Chk",
                            PaymentMethodName = "Check"
                        },
                        new
                        {
                            PaymentMethodId = "Disc",
                            PaymentMethodName = "Discover"
                        },
                        new
                        {
                            PaymentMethodId = "MC",
                            PaymentMethodName = "Mastercard"
                        },
                        new
                        {
                            PaymentMethodId = "Visa",
                            PaymentMethodName = "Visa"
                        },
                        new
                        {
                            PaymentMethodId = "Other",
                            PaymentMethodName = "Other"
                        });
                });

            modelBuilder.Entity("GalaAuction.Server.Models.Bidder", b =>
                {
                    b.HasOne("GalaAuction.Server.Models.Guest", "Guest")
                        .WithMany("Bidders")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("GalaAuction.Server.Models.Guest", b =>
                {
                    b.HasOne("GalaAuction.Server.Models.GalaEvent", "GalaEvent")
                        .WithMany("Guests")
                        .HasForeignKey("GalaEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GalaEvent");
                });

            modelBuilder.Entity("GalaAuction.Server.Models.Item", b =>
                {
                    b.HasOne("GalaAuction.Server.Models.Category", null)
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.HasOne("GalaAuction.Server.Models.GalaEvent", "GalaEvent")
                        .WithMany("Items")
                        .HasForeignKey("GalaEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalaAuction.Server.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Items")
                        .HasForeignKey("PaymentMethodId");

                    b.Navigation("GalaEvent");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("GalaAuction.Server.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GalaAuction.Server.Models.GalaEvent", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("GalaAuction.Server.Models.Guest", b =>
                {
                    b.Navigation("Bidders");
                });

            modelBuilder.Entity("GalaAuction.Server.Models.PaymentMethod", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
